-- Replace <APP_DB_USER> with the Dashboard connection-string user.
-- Helper discovery:
-- SELECT usename
-- FROM pg_stat_activity
-- WHERE datname = 'todo_saas'
-- GROUP BY usename
-- ORDER BY usename;

GRANT USAGE ON SCHEMA reup TO "<APP_DB_USER>";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA reup TO "<APP_DB_USER>";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA reup TO "<APP_DB_USER>";

ALTER DEFAULT PRIVILEGES IN SCHEMA reup
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "<APP_DB_USER>";

ALTER DEFAULT PRIVILEGES IN SCHEMA reup
GRANT USAGE, SELECT ON SEQUENCES TO "<APP_DB_USER>";
