BEGIN;
SET LOCAL statement_timeout = '5min';
SET LOCAL lock_timeout = '10s';
SELECT pg_advisory_xact_lock(hashtext('ai-core-reset'));

-- Generated from docs/database-refactor/providers-before.csv and capabilities-before.csv.
-- Contains provider/model metadata and config references only. No credential secret values are stored here.

INSERT INTO public.todox_ai_provider (provider_code, provider_name, provider_type, base_url, api_key_config_name, auth_type, enabled, is_system, priority, description, config_json, created_by, updated_by)
VALUES ('openrouter', 'OpenRouter', 'external_api', 'https://openrouter.ai/api/v1', 'OpenRouter__ApiKey', 'bearer', true, true, 10, 'OpenRouter unified AI API provider for image and video generation models.', COALESCE('{"headers": {"appTitleConfigName": "OpenRouter:AppTitle", "httpRefererConfigName": "OpenRouter:HttpReferer"}, "imageEndpoint": "/images", "videoEndpoint": "/videos", "defaultImageModel": "bytedance-seed/seedream-4.5", "defaultVideoModel": "google/veo-3.1"}'::jsonb, '{}'::jsonb), 'ai_core_reset', 'ai_core_reset')
ON CONFLICT (provider_code) DO UPDATE
SET provider_name = EXCLUDED.provider_name, provider_type = EXCLUDED.provider_type, base_url = EXCLUDED.base_url, api_key_config_name = EXCLUDED.api_key_config_name, auth_type = EXCLUDED.auth_type, enabled = EXCLUDED.enabled, is_system = EXCLUDED.is_system, priority = EXCLUDED.priority, description = EXCLUDED.description, config_json = EXCLUDED.config_json, updated_by = EXCLUDED.updated_by, updated_at = now();

INSERT INTO public.todox_ai_provider (provider_code, provider_name, provider_type, base_url, api_key_config_name, auth_type, enabled, is_system, priority, description, config_json, created_by, updated_by)
VALUES ('image_ai_creative_render', 'ImageAICreativeRender', 'internal_api', NULL, NULL, 'custom', true, true, 20, 'Internal TodoX image/avatar creative render provider.', COALESCE('{}'::jsonb, '{}'::jsonb), 'ai_core_reset', 'ai_core_reset')
ON CONFLICT (provider_code) DO UPDATE
SET provider_name = EXCLUDED.provider_name, provider_type = EXCLUDED.provider_type, base_url = EXCLUDED.base_url, api_key_config_name = EXCLUDED.api_key_config_name, auth_type = EXCLUDED.auth_type, enabled = EXCLUDED.enabled, is_system = EXCLUDED.is_system, priority = EXCLUDED.priority, description = EXCLUDED.description, config_json = EXCLUDED.config_json, updated_by = EXCLUDED.updated_by, updated_at = now();

INSERT INTO public.todox_ai_provider (provider_code, provider_name, provider_type, base_url, api_key_config_name, auth_type, enabled, is_system, priority, description, config_json, created_by, updated_by)
VALUES ('yescale_task_image', 'YEScale Task Image', 'external_api', 'https://api.yescale.io', 'AiProviders__YEScale__AccessKey', 'bearer', true, true, 40, 'YEScale async task image provider. Credentials must come from secret store/environment.', COALESCE('{"protocol": "yescale_task", "submit_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "poll_endpoint_template": "/task/{task_id}", "poll_terminal_statuses": ["SUCCESS", "FAILURE"]}'::jsonb, '{}'::jsonb), 'ai_core_reset', 'ai_core_reset')
ON CONFLICT (provider_code) DO UPDATE
SET provider_name = EXCLUDED.provider_name, provider_type = EXCLUDED.provider_type, base_url = EXCLUDED.base_url, api_key_config_name = EXCLUDED.api_key_config_name, auth_type = EXCLUDED.auth_type, enabled = EXCLUDED.enabled, is_system = EXCLUDED.is_system, priority = EXCLUDED.priority, description = EXCLUDED.description, config_json = EXCLUDED.config_json, updated_by = EXCLUDED.updated_by, updated_at = now();

INSERT INTO public.todox_ai_provider (provider_code, provider_name, provider_type, base_url, api_key_config_name, auth_type, enabled, is_system, priority, description, config_json, created_by, updated_by)
VALUES ('yescale_task_video', 'YEScale Task Video', 'external_api', 'https://api.yescale.io', 'AiProviders__YEScale__AccessKey', 'bearer', true, true, 45, 'YEScale async task video provider. Runtime credential comes from environment.', COALESCE('{"protocol": "yescale_task", "submit_endpoint": "/task/submit", "poll_endpoint_template": "/task/{task_id}", "poll_terminal_statuses": ["SUCCESS", "FAILURE", "CANCELLED", "EXPIRED"]}'::jsonb, '{}'::jsonb), 'ai_core_reset', 'ai_core_reset')
ON CONFLICT (provider_code) DO UPDATE
SET provider_name = EXCLUDED.provider_name, provider_type = EXCLUDED.provider_type, base_url = EXCLUDED.base_url, api_key_config_name = EXCLUDED.api_key_config_name, auth_type = EXCLUDED.auth_type, enabled = EXCLUDED.enabled, is_system = EXCLUDED.is_system, priority = EXCLUDED.priority, description = EXCLUDED.description, config_json = EXCLUDED.config_json, updated_by = EXCLUDED.updated_by, updated_at = now();

INSERT INTO public.todox_ai_provider (provider_code, provider_name, provider_type, base_url, api_key_config_name, auth_type, enabled, is_system, priority, description, config_json, created_by, updated_by)
VALUES ('kie', 'KIE', 'external_api', 'https://api.kie.ai', 'KIE_API_KEY', 'bearer', false, true, 80, 'KIE provider for Kling motion-control video. Phase 1 disabled by default; API key must come from environment/secret store.', COALESCE('{"phase": "phase1_no_billing", "feature_code": "dance_sell", "poll_endpoint": "/api/v1/jobs/recordInfo", "submit_endpoint": "/api/v1/jobs/createTask", "max_concurrent_tasks": 100, "rate_limit_requests_per_10s": 20}'::jsonb, '{}'::jsonb), 'ai_core_reset', 'ai_core_reset')
ON CONFLICT (provider_code) DO UPDATE
SET provider_name = EXCLUDED.provider_name, provider_type = EXCLUDED.provider_type, base_url = EXCLUDED.base_url, api_key_config_name = EXCLUDED.api_key_config_name, auth_type = EXCLUDED.auth_type, enabled = EXCLUDED.enabled, is_system = EXCLUDED.is_system, priority = EXCLUDED.priority, description = EXCLUDED.description, config_json = EXCLUDED.config_json, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'openrouter')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'openrouter', 'avatar_generation', 'OpenRouter Avatar Generation', 'Generate avatar images using OpenRouter image models.', 'bytedance-seed/seedream-4.5', 'Seedream 4.5', NULL, 'image', 3.000000, 3.000000, false, true, true, 10, NULL, NULL, COALESCE('{"quality": "high", "resolution": "2K", "output_format": "png"}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/images', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'openrouter')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'openrouter', 'chibi_avatar_generation', 'OpenRouter Chibi Avatar Generation', 'Generate chibi avatar images using OpenRouter image models.', 'bytedance-seed/seedream-4.5', 'Seedream 4.5', NULL, 'image', 3.000000, 3.000000, false, true, false, 10, NULL, NULL, COALESCE('{"quality": "high", "resolution": "2K", "output_format": "png"}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/images', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'openrouter')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'openrouter', 'character_generation', 'OpenRouter Character Generation', 'Generate reusable AI character master images using OpenRouter image models.', 'bytedance-seed/seedream-4.5', 'Seedream 4.5', NULL, 'image', 3.000000, 3.000000, false, true, false, 10, NULL, NULL, COALESCE('{"quality": "high", "resolution": "2K", "output_format": "png"}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/images', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'openrouter')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'openrouter', 'poster_generation', 'OpenRouter Poster Generation', 'Generate posters or thumbnails using OpenRouter image models.', 'bytedance-seed/seedream-4.5', 'Seedream 4.5', NULL, 'image', 3.000000, 3.000000, false, true, true, 20, NULL, NULL, COALESCE('{"method": "POST", "quality": "high", "endpoint": "/images", "resolution": "1K", "outputFormat": "png", "defaultQuality": "high", "supportsPrompt": true, "defaultResolution": "1K", "supportsStreaming": false, "defaultAspectRatio": "16:9", "defaultOutputFormat": "png", "supportsHttpReference": true, "supportsReferenceImage": true, "supportsBase64Reference": true}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/images', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'openrouter')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'openrouter', 'thumbnail_generation', 'OpenRouter Thumbnail Generation', 'Generate service thumbnails using OpenRouter image models.', 'bytedance-seed/seedream-4.5', 'Seedream 4.5', NULL, 'image', 3.000000, 3.000000, false, true, true, 20, NULL, NULL, COALESCE('{"method": "POST", "quality": "high", "endpoint": "/images", "resolution": "1K", "outputFormat": "png", "defaultQuality": "high", "supportsPrompt": true, "defaultResolution": "1K", "supportsStreaming": false, "defaultAspectRatio": "9:16", "defaultOutputFormat": "png", "supportsHttpReference": true, "supportsReferenceImage": true, "supportsBase64Reference": true}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/images', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'openrouter')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'openrouter', 'text_to_video', 'OpenRouter Prompt To Video', 'Create video from text prompt and optional reference image using OpenRouter Video API.', 'google/veo-3.1', 'Google Veo 3.1', NULL, 'second', 1.000000, 1.000000, true, true, true, 10, NULL, NULL, COALESCE('{"async": true, "method": "POST", "polling": true, "endpoint": "/videos", "maxDuration": 30, "minDuration": 5, "supportsPrompt": true, "defaultDuration": 8, "defaultResolution": "720p", "defaultAspectRatio": "16:9", "supportsAudioReference": "provider_dependent", "supportsImageReference": true, "supportsVideoReference": "provider_dependent", "initiallyDisabledUntilTested": true}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/images', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'openrouter')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'openrouter', 'image_to_video', 'OpenRouter Image To Video', 'Create video from prompt plus reference image/frame using OpenRouter Video API.', 'google/veo-3.1', 'Google Veo 3.1', NULL, 'second', 1.000000, 1.000000, false, true, true, 10, NULL, NULL, COALESCE('{"async": true, "method": "POST", "polling": true, "endpoint": "/videos", "maxDuration": 30, "minDuration": 5, "supportsPrompt": true, "defaultDuration": 8, "defaultResolution": "720p", "defaultAspectRatio": "16:9", "supportsAudioReference": "provider_dependent", "supportsImageReference": true, "supportsVideoReference": "provider_dependent", "initiallyDisabledUntilTested": true}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/images', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'image_ai_creative_render')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'image_ai_creative_render', 'avatar_generation', 'ImageAICreativeRender Avatar Generation', 'Generate avatar images using internal ImageAICreativeRender provider.', 'internal_default', 'Internal Default', NULL, 'image', 3.000000, 3.000000, true, true, true, 20, NULL, NULL, COALESCE('{}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), NULL, 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'image_ai_creative_render')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'image_ai_creative_render', 'chibi_avatar_generation', 'ImageAICreativeRender Chibi Avatar Generation', 'Generate chibi avatars using internal ImageAICreativeRender provider.', 'internal_default', 'Internal Default', NULL, 'image', 3.000000, 3.000000, true, true, true, 20, NULL, NULL, COALESCE('{}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), NULL, 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'image_ai_creative_render')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'image_ai_creative_render', 'character_generation', 'ImageAICreativeRender Character Generation', 'Generate reusable AI character master images using internal ImageAICreativeRender provider.', 'internal_default', 'Internal Default', NULL, 'image', 3.000000, 3.000000, true, true, true, 20, NULL, NULL, COALESCE('{}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), NULL, 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'openrouter')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'openrouter', 'image_generation', 'OpenRouter Image Generation', 'Create images from text prompts and optional reference images using OpenRouter Image API.', 'bytedance-seed/seedream-4.5', 'Seedream 4.5', NULL, 'image', 3.000000, 3.000000, false, true, false, 5, NULL, NULL, COALESCE('{"quality": "high", "resolution": "2K", "output_format": "png"}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/images', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'image_generation', 'YEScale image_generation / default / nano-banana-2', NULL, 'nano-banana-2', NULL, NULL, 'request', 0.064000, 0.000000, true, true, true, 100, NULL, NULL, COALESCE('{"size": "1K", "quality": null, "thinking": "minimal", "cost_source": "configured_tariff", "model_sizes": {"seedream-5": "2K"}, "routing_role": "default", "google_search": "disable", "point_formula": "usd * 8000 / 10000", "model_profiles": {"seedream-5": "seedream_5"}, "verified_async": true, "adapter_profile": "nano_banana_2", "fallback_models": ["seedream-5"], "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.08, "transient_terminal_error_codes": ["rate_limit", "temporarily_unavailable"]}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'image_generation', 'YEScale image_generation / backup / seedream-5', NULL, 'seedream-5', NULL, NULL, 'request', 0.052000, 0.000000, false, false, true, 100, NULL, NULL, COALESCE('{"size": "2K", "quality": null, "cost_source": "configured_tariff", "routing_role": "backup", "point_formula": "usd * 8000 / 10000", "verified_async": true, "adapter_profile": "seedream_5", "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.065}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'image_generation', 'YEScale image_generation / cheap / gpt-image', NULL, 'gpt-image', NULL, NULL, 'request', 0.019200, 0.000000, false, true, true, 100, NULL, NULL, COALESCE('{"size": "1024x1024", "quality": "low", "background": "transparent", "cost_source": "configured_tariff", "routing_role": "cheap", "point_formula": "usd * 8000 / 10000", "verified_async": true, "adapter_profile": "gpt_image", "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.024}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'avatar_generation', 'YEScale avatar_generation / default / nano-banana-2', NULL, 'nano-banana-2', NULL, NULL, 'request', 0.064000, 0.000000, false, true, true, 100, NULL, NULL, COALESCE('{"size": "1K", "quality": null, "thinking": "minimal", "cost_source": "configured_tariff", "model_sizes": {"seedream-5": "2K"}, "routing_role": "default", "google_search": "disable", "point_formula": "usd * 8000 / 10000", "model_profiles": {"seedream-5": "seedream_5"}, "verified_async": true, "adapter_profile": "nano_banana_2", "fallback_models": ["seedream-5"], "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.08, "transient_terminal_error_codes": ["rate_limit", "temporarily_unavailable"]}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'avatar_generation', 'YEScale avatar_generation / cheap / gpt-image', NULL, 'gpt-image', NULL, NULL, 'request', 0.019200, 0.000000, false, true, true, 100, NULL, NULL, COALESCE('{"size": "1024x1024", "quality": "low", "background": "transparent", "cost_source": "configured_tariff", "routing_role": "cheap", "point_formula": "usd * 8000 / 10000", "verified_async": true, "adapter_profile": "gpt_image", "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.024}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'avatar_generation', 'YEScale avatar_generation / backup / seedream-5', NULL, 'seedream-5', NULL, NULL, 'request', 0.052000, 0.000000, false, false, true, 100, NULL, NULL, COALESCE('{"size": "2K", "quality": null, "cost_source": "configured_tariff", "routing_role": "backup", "point_formula": "usd * 8000 / 10000", "verified_async": true, "adapter_profile": "seedream_5", "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.065}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'chibi_avatar_generation', 'YEScale chibi_avatar_generation / default / nano-banana-2', NULL, 'nano-banana-2', NULL, NULL, 'request', 0.064000, 0.000000, false, true, true, 100, NULL, NULL, COALESCE('{"size": "1K", "quality": null, "thinking": "minimal", "cost_source": "configured_tariff", "model_sizes": {"seedream-5": "2K"}, "routing_role": "default", "google_search": "disable", "point_formula": "usd * 8000 / 10000", "model_profiles": {"seedream-5": "seedream_5"}, "verified_async": true, "adapter_profile": "nano_banana_2", "fallback_models": ["seedream-5"], "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.08, "transient_terminal_error_codes": ["rate_limit", "temporarily_unavailable"]}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'chibi_avatar_generation', 'YEScale chibi_avatar_generation / cheap / gpt-image', NULL, 'gpt-image', NULL, NULL, 'request', 0.019200, 0.000000, false, true, true, 100, NULL, NULL, COALESCE('{"size": "1024x1024", "quality": "low", "background": "transparent", "cost_source": "configured_tariff", "routing_role": "cheap", "point_formula": "usd * 8000 / 10000", "verified_async": true, "adapter_profile": "gpt_image", "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.024}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'chibi_avatar_generation', 'YEScale chibi_avatar_generation / backup / seedream-5', NULL, 'seedream-5', NULL, NULL, 'request', 0.052000, 0.000000, false, false, true, 100, NULL, NULL, COALESCE('{"size": "2K", "quality": null, "cost_source": "configured_tariff", "routing_role": "backup", "point_formula": "usd * 8000 / 10000", "verified_async": true, "adapter_profile": "seedream_5", "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.065}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'character_generation', 'YEScale character_generation / default / nano-banana-2', NULL, 'nano-banana-2', NULL, NULL, 'request', 0.064000, 0.000000, false, true, true, 100, NULL, NULL, COALESCE('{"size": "1K", "quality": null, "thinking": "minimal", "cost_source": "configured_tariff", "model_sizes": {"seedream-5": "2K"}, "routing_role": "default", "google_search": "disable", "point_formula": "usd * 8000 / 10000", "model_profiles": {"seedream-5": "seedream_5"}, "verified_async": true, "adapter_profile": "nano_banana_2", "fallback_models": ["seedream-5"], "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.08, "transient_terminal_error_codes": ["rate_limit", "temporarily_unavailable"]}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'character_generation', 'YEScale character_generation / cheap / gpt-image', NULL, 'gpt-image', NULL, NULL, 'request', 0.019200, 0.000000, false, true, true, 100, NULL, NULL, COALESCE('{"size": "1024x1024", "quality": "low", "background": "transparent", "cost_source": "configured_tariff", "routing_role": "cheap", "point_formula": "usd * 8000 / 10000", "verified_async": true, "adapter_profile": "gpt_image", "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.024}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'character_generation', 'YEScale character_generation / backup / seedream-5', NULL, 'seedream-5', NULL, NULL, 'request', 0.052000, 0.000000, false, false, true, 100, NULL, NULL, COALESCE('{"size": "2K", "quality": null, "cost_source": "configured_tariff", "routing_role": "backup", "point_formula": "usd * 8000 / 10000", "verified_async": true, "adapter_profile": "seedream_5", "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.065}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'scene_image_generation', 'YEScale scene_image_generation / default / nano-banana-2', NULL, 'nano-banana-2', NULL, NULL, 'request', 0.064000, 0.000000, false, true, true, 100, NULL, NULL, COALESCE('{"size": "1K", "quality": null, "thinking": "minimal", "cost_source": "configured_tariff", "model_sizes": {"seedream-5": "2K"}, "routing_role": "default", "google_search": "disable", "point_formula": "usd * 8000 / 10000", "model_profiles": {"seedream-5": "seedream_5"}, "verified_async": true, "adapter_profile": "nano_banana_2", "fallback_models": ["seedream-5"], "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.08, "transient_terminal_error_codes": ["rate_limit", "temporarily_unavailable"]}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'scene_image_generation', 'YEScale scene_image_generation / cheap / gpt-image', NULL, 'gpt-image', NULL, NULL, 'request', 0.019200, 0.000000, false, true, true, 100, NULL, NULL, COALESCE('{"size": "1024x1024", "quality": "low", "background": "transparent", "cost_source": "configured_tariff", "routing_role": "cheap", "point_formula": "usd * 8000 / 10000", "verified_async": true, "adapter_profile": "gpt_image", "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.024}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'scene_image_generation', 'YEScale scene_image_generation / backup / seedream-5', NULL, 'seedream-5', NULL, NULL, 'request', 0.052000, 0.000000, false, false, true, 100, NULL, NULL, COALESCE('{"size": "2K", "quality": null, "cost_source": "configured_tariff", "routing_role": "backup", "point_formula": "usd * 8000 / 10000", "verified_async": true, "adapter_profile": "seedream_5", "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.065}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'poster_generation', 'YEScale poster_generation / default / nano-banana-2', NULL, 'nano-banana-2', NULL, NULL, 'request', 0.064000, 0.000000, true, true, true, 100, NULL, NULL, COALESCE('{"size": "1K", "quality": null, "thinking": "minimal", "cost_source": "configured_tariff", "model_sizes": {"seedream-5": "2K"}, "routing_role": "default", "google_search": "disable", "point_formula": "usd * 8000 / 10000", "model_profiles": {"seedream-5": "seedream_5"}, "verified_async": true, "adapter_profile": "nano_banana_2", "fallback_models": ["seedream-5"], "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.08, "transient_terminal_error_codes": ["rate_limit", "temporarily_unavailable"]}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'poster_generation', 'YEScale poster_generation / cheap / gpt-image', NULL, 'gpt-image', NULL, NULL, 'request', 0.019200, 0.000000, false, true, true, 100, NULL, NULL, COALESCE('{"size": "1024x1024", "quality": "low", "background": "transparent", "cost_source": "configured_tariff", "routing_role": "cheap", "point_formula": "usd * 8000 / 10000", "verified_async": true, "adapter_profile": "gpt_image", "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.024}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'poster_generation', 'YEScale poster_generation / backup / seedream-5', NULL, 'seedream-5', NULL, NULL, 'request', 0.052000, 0.000000, false, false, true, 100, NULL, NULL, COALESCE('{"size": "2K", "quality": null, "cost_source": "configured_tariff", "routing_role": "backup", "point_formula": "usd * 8000 / 10000", "verified_async": true, "adapter_profile": "seedream_5", "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.065}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'thumbnail_generation', 'YEScale thumbnail_generation / default / nano-banana-2', NULL, 'nano-banana-2', NULL, NULL, 'request', 0.064000, 0.000000, true, true, true, 100, NULL, NULL, COALESCE('{"size": "1K", "quality": null, "thinking": "minimal", "cost_source": "configured_tariff", "model_sizes": {"seedream-5": "2K"}, "routing_role": "default", "google_search": "disable", "point_formula": "usd * 8000 / 10000", "model_profiles": {"seedream-5": "seedream_5"}, "verified_async": true, "adapter_profile": "nano_banana_2", "fallback_models": ["seedream-5"], "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.08, "transient_terminal_error_codes": ["rate_limit", "temporarily_unavailable"]}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'thumbnail_generation', 'YEScale thumbnail_generation / cheap / gpt-image', NULL, 'gpt-image', NULL, NULL, 'request', 0.019200, 0.000000, false, true, true, 100, NULL, NULL, COALESCE('{"size": "1024x1024", "quality": "low", "background": "transparent", "cost_source": "configured_tariff", "routing_role": "cheap", "point_formula": "usd * 8000 / 10000", "verified_async": true, "adapter_profile": "gpt_image", "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.024}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_image')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_image', 'thumbnail_generation', 'YEScale thumbnail_generation / backup / seedream-5', NULL, 'seedream-5', NULL, NULL, 'request', 0.052000, 0.000000, false, false, true, 100, NULL, NULL, COALESCE('{"size": "2K", "quality": null, "cost_source": "configured_tariff", "routing_role": "backup", "point_formula": "usd * 8000 / 10000", "verified_async": true, "adapter_profile": "seedream_5", "verified_endpoint": "/task/submit", "mcp_verified_at_utc": "2026-07-15T18:53:03.6516197Z", "provider_estimated_cost_usd": 0.065}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'image_ai_creative_render')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'image_ai_creative_render', 'scene_image_generation', 'ImageAICreativeRender Scene Generation', 'Render static scene images using internal ImageAICreativeRender provider.', 'internal_default', 'Internal Default', NULL, 'image', 3.000000, 3.000000, true, true, true, 20, NULL, NULL, COALESCE('{"seed_source": "manual_sql", "feature_code": "scene_image_render", "source_capability": "character_generation"}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), NULL, 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'yescale_task_video')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'yescale_task_video', 'image_to_video', 'YEScale image_to_video / omni-flash', 'Render scene video from the selected image using YEScale Omni Flash.', 'omni-flash', NULL, NULL, 'request', 0.296000, 0.296000, true, true, true, 100, NULL, NULL, COALESCE('{"mode": "i2v(img_ref)", "pricing": {"rules": [{"match": {"mode": "i2v(img_ref)", "model": "omni-flash"}, "ruleKey": "omni-flash|i2v(img_ref)", "costSource": "configured_tariff", "chargedPoints": 0.296, "providerEstimatedCostUsd": 0.37}, {"match": {"mode": "v2v", "model": "omni-flash"}, "ruleKey": "omni-flash|v2v", "costSource": "configured_tariff", "chargedPoints": 0.376, "providerEstimatedCostUsd": 0.47}]}, "cost_source": "configured_tariff", "aspect_ratios": ["16:9", "9:16"], "supported_modes": ["t2v", "i2v(img_ref)", "i2v(first_last_frame)", "v2v"], "max_prompt_characters": 4096, "provider_estimated_cost_usd": 0.37}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/task/submit', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'kie')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, description, model_name, model_display_name, model_version, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, max_quantity, min_quantity, config_json, pricing_json, endpoint_path, created_by, updated_by)
SELECT id, 'kie', 'motion_control_video', 'Kling 2.6 Motion Control', NULL, 'kling-2.6/motion-control', NULL, NULL, 'request', 0.000000, 0.000000, false, false, false, 100, NULL, NULL, COALESCE('{"phase": "phase1_no_billing", "default_mode": "720p", "feature_code": "dance_sell", "allowed_modes": ["720p"], "poll_endpoint": "/api/v1/jobs/recordInfo", "pricing_status": "not_verified", "billing_enabled": false, "allowed_character_orientations": ["image"]}'::jsonb, '{}'::jsonb), COALESCE(NULL::jsonb, '{}'::jsonb), '/api/v1/jobs/createTask', 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET display_name = EXCLUDED.display_name, description = EXCLUDED.description, model_display_name = EXCLUDED.model_display_name, model_version = EXCLUDED.model_version, unit_type = EXCLUDED.unit_type, unit_cost_points = EXCLUDED.unit_cost_points, minimum_points = EXCLUDED.minimum_points, is_default = EXCLUDED.is_default, allow_user_select = EXCLUDED.allow_user_select, enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, max_quantity = EXCLUDED.max_quantity, min_quantity = EXCLUDED.min_quantity, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, endpoint_path = EXCLUDED.endpoint_path, updated_by = EXCLUDED.updated_by, updated_at = now();

-- Required Dance Sell reference model not present in the pre-reset provider catalog.
WITH provider_row AS (SELECT id FROM public.todox_ai_provider WHERE provider_code = 'kie')
INSERT INTO public.todox_ai_provider_capability (provider_id, provider_code, capability_code, display_name, model_name, model_display_name, unit_type, unit_cost_points, minimum_points, is_default, allow_user_select, enabled, priority, endpoint_path, config_json, pricing_json, created_by, updated_by)
SELECT id, 'kie', 'dance_sell_reference_image', 'Dance Sell Reference Image', 'gpt-image-2-image-to-image', 'GPT Image 2 Image To Image', 'credits', 0, 0, true, true, true, 100, '/api/v1/jobs/createTask', '{"operation_type":"reference_image","input_urls":2,"default_aspect_ratio":"1:1","poll_endpoint":"/api/v1/jobs/recordInfo"}'::jsonb, '{"pricing_status":"requires_verification","usage_unit":"credits"}'::jsonb, 'ai_core_reset', 'ai_core_reset' FROM provider_row
ON CONFLICT (provider_id, capability_code, model_name) DO UPDATE
SET enabled = EXCLUDED.enabled, allow_user_select = EXCLUDED.allow_user_select, endpoint_path = EXCLUDED.endpoint_path, config_json = EXCLUDED.config_json, pricing_json = EXCLUDED.pricing_json, updated_by = EXCLUDED.updated_by, updated_at = now();

COMMIT;
