-- TodoX SaaS Sprint 2B
-- Database: todo_saas
-- Purpose: account foundation for admin users, customers, and customer login accounts.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS system_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(100) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(50),
    password_hash TEXT NOT NULL,
    role_code VARCHAR(50) NOT NULL DEFAULT 'Admin',
    status_code VARCHAR(50) NOT NULL DEFAULT 'Active',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS customers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_code VARCHAR(50) NOT NULL UNIQUE,
    company_name VARCHAR(255) NOT NULL,
    contact_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    tax_code VARCHAR(50),
    address TEXT,
    status_code VARCHAR(50) NOT NULL DEFAULT 'Active',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS customer_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(50),
    password_hash TEXT NOT NULL,
    role_code VARCHAR(50) NOT NULL DEFAULT 'CustomerOwner',
    status_code VARCHAR(50) NOT NULL DEFAULT 'Active',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS ix_customers_status_code ON customers(status_code);
CREATE INDEX IF NOT EXISTS ix_customer_accounts_customer_id ON customer_accounts(customer_id);
CREATE INDEX IF NOT EXISTS ix_customer_accounts_status_code ON customer_accounts(status_code);

-- NOTE: bcrypt hash should be generated by application in production.
-- Temporary seed uses plain marker hash text for Sprint 2B planning.
INSERT INTO system_users (id, username, full_name, email, phone, password_hash, role_code, status_code)
VALUES (
    '11111111-1111-1111-1111-111111111111',
    'admin',
    'Admin System',
    'admin@todox.local',
    '0901234567',
    'TODO_REPLACE_WITH_BCRYPT_HASH_OF_toDOx@123#2026',
    'Admin',
    'Active'
)
ON CONFLICT (username) DO NOTHING;

INSERT INTO customers (id, customer_code, company_name, contact_name, email, phone, tax_code, address, status_code)
VALUES (
    '22222222-2222-2222-2222-222222222222',
    'CUST-0001',
    'Công ty Demo TodoX',
    'Nguyễn Văn A',
    'demo@todox.local',
    '0912345678',
    '0100000001',
    'TP. Hồ Chí Minh',
    'Active'
)
ON CONFLICT (customer_code) DO NOTHING;

INSERT INTO customer_accounts (id, customer_id, full_name, email, phone, password_hash, role_code, status_code)
VALUES (
    '33333333-3333-3333-3333-333333333333',
    '22222222-2222-2222-2222-222222222222',
    'Nguyễn Văn A',
    'demo@todox.local',
    '0912345678',
    'TODO_REPLACE_WITH_BCRYPT_HASH_OF_Customer@123',
    'CustomerOwner',
    'Active'
)
ON CONFLICT (email) DO NOTHING;
