using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Extensions.Options;
using TodoX.Web.Models;
using TodoX.Web.Services.VideoRender;
using Xunit;
namespace TodoX.Web.Tests;
public sealed class RVideoP3B2Tests
{
    private static string WebRoot => Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..","..","..","..","TodoX.Web"));
    private static string Read(params string[] p) => File.ReadAllText(Path.Combine(new[]{WebRoot}.Concat(p).ToArray()));
    private static AiProviderModelListItemDto M(string code,bool allow,bool deprecated,int[] durations,string providerCode="79ai"){
        var m=new AiProviderModelListItemDto{Id=Random.Shared.Next(1,100000),ProviderId=1,ProviderCode=providerCode,ProviderModelCode=code,DisplayName=code,MediaType="video",Enabled=true,AllowUserSelect=allow,IsDeprecated=deprecated};
        m.SupportedDurations=durations.ToList();m.SupportedModes=new List<string>();return m;}
    private static IReadOnlyList<AiProviderModelListItemDto> BuildCatalog()=> new List<AiProviderModelListItemDto>{M("veo_omni",true,false,new[]{4,8}),M("veo_3_1",true,false,new[]{6,8,10}),M("grok_video_heavy",true,false,new[]{5,10})};
    [Fact] public void Filtering_AllowUserSelect_False_Excluded(){var list=new List<AiProviderModelListItemDto>{M("veo_omni",false,false,new[]{8})};Assert.Empty(RVideoSceneVideoModelOptionsService.BuildOptions(list));}
    [Fact] public void Filtering_IsDeprecated_True_Excluded(){var list=new List<AiProviderModelListItemDto>{M("veo_omni",true,true,new[]{8})};Assert.Empty(RVideoSceneVideoModelOptionsService.BuildOptions(list));}
    [Fact] public void Filtering_AllowTrue_NotDeprecated_Included(){var list=new List<AiProviderModelListItemDto>{M("veo_omni",true,false,new[]{8})};Assert.Single(RVideoSceneVideoModelOptionsService.BuildOptions(list));}
    [Fact] public void Ordering_FollowsPolicy(){var opts=RVideoSceneVideoModelOptionsService.BuildOptions(BuildCatalog());var expected=RVideoVideoModelPolicy.Models.Select(x=>$"{x.ProviderCode}|{x.Model}|{x.Mode}").ToList();var actual=opts.Select(x=>x.Key.ToLowerInvariant()).ToList();var indices=expected.Select(e=>actual.IndexOf(e.ToLowerInvariant())).ToList();Assert.All(indices,i=>Assert.True(i>=0));for(int i=1;i<indices.Count;i++) Assert.True(indices[i]>indices[i-1],$"Order violated at {i}");}
    [Fact] public void PerModelDurations_RemainModelSpecific(){var opts=RVideoSceneVideoModelOptionsService.BuildOptions(BuildCatalog());var veo=opts.First(x=>x.ModelCode=="veo_omni");var grok=opts.First(x=>x.ModelCode=="grok_video_heavy");Assert.Equal(new[]{4,8},veo.Durations.ToArray());Assert.Equal(new[]{5,10},grok.Durations.ToArray());}
    [Fact] public void ResolveNearestDuration_Behavior(){var sup=new[]{5,8,10} as IReadOnlyList<int>;Assert.Equal(5,RVideoSceneVideoModelOptionsService.ResolveNearestDuration(3,sup));Assert.Equal(8,RVideoSceneVideoModelOptionsService.ResolveNearestDuration(6,sup));Assert.Equal(10,RVideoSceneVideoModelOptionsService.ResolveNearestDuration(10,sup));Assert.Equal(10,RVideoSceneVideoModelOptionsService.ResolveNearestDuration(99,sup));Assert.Equal(7,RVideoSceneVideoModelOptionsService.ResolveNearestDuration(7,Array.Empty<int>()));}
    private sealed class FakeOpt : IRVideoSceneVideoModelOptionsService{private readonly IReadOnlyList<SceneVideoModelOption> _c;public FakeOpt(IReadOnlyList<SceneVideoModelOption> c)=>_c=c;public Task<IReadOnlyList<SceneVideoModelOption>> GetOptionsAsync(CancellationToken ct=default)=>Task.FromResult(_c);public Task<IReadOnlyList<int>> GetAllDurationsAsync(CancellationToken ct=default)=>Task.FromResult<IReadOnlyList<int>>(_c.SelectMany(x=>x.Durations).Distinct().OrderBy(x=>x).ToList());public IReadOnlyList<SceneVideoModelOption> GetCachedOptions()=>_c;}
    private static ScenePromptMetadata ValidMeta(string? k=null,string? d=null){var m=new ScenePromptMetadata{ImagePrompt="a photo of a cat",MotionPrompt="cat moves",ScenePurpose="test",EffectiveImagePrompt="a photo of a cat"};if(k!=null) m.Extra["video_model"]=k;if(d!=null) m.Extra["video_duration"]=d;return m;}
    private static IReadOnlyList<SceneVideoModelOption> FakeCached()=>RVideoSceneVideoModelOptionsService.BuildOptions(BuildCatalog());
    [Fact] public void Validator_CaseA_MissingModel_Requires(){var svc=new FakeOpt(FakeCached());var v=new RVideoSceneDraftValidator(svc);var r=v.Validate(ValidMeta(null,null));Assert.False(r.IsValid);Assert.Equal("VIDEO_MODEL_REQUIRED",r.ErrorCode);}
    [Fact] public void Validator_CaseB_InvalidModel_Requires(){var svc=new FakeOpt(FakeCached());var v=new RVideoSceneDraftValidator(svc);var r=v.Validate(ValidMeta("bad|model|key",null));Assert.False(r.IsValid);Assert.Equal("VIDEO_MODEL_REQUIRED",r.ErrorCode);}
    [Fact] public void Validator_CaseC_ValidModel_UnsupportedDuration_Fails(){var svc=new FakeOpt(FakeCached());var v=new RVideoSceneDraftValidator(svc);var key=FakeCached().First(x=>x.ModelCode=="veo_omni").Key;var r=v.Validate(ValidMeta(key,"999"));Assert.False(r.IsValid);Assert.Equal("VIDEO_DURATION_UNSUPPORTED",r.ErrorCode);}
    [Fact] public void Validator_CaseD_ValidModel_SupportedDuration_Ok(){var svc=new FakeOpt(FakeCached());var v=new RVideoSceneDraftValidator(svc);var opt=FakeCached().First(x=>x.ModelCode=="veo_omni");var r=v.Validate(ValidMeta(opt.Key,opt.Durations.First().ToString()));Assert.True(r.IsValid);var r2=v.Validate(ValidMeta(opt.Key,null),opt.Durations.First());Assert.True(r2.IsValid);var r3=v.Validate(ValidMeta(opt.Key,null),999);Assert.False(r3.IsValid);Assert.Equal("VIDEO_DURATION_UNSUPPORTED",r3.ErrorCode);}
    [Fact] public void Metadata_RoundTrip_Extra_Survives(){var m=new ScenePromptMetadata{ScenePurpose="p",ImagePrompt="img",MotionPrompt="mot",Voice="v"};m.Extra["video_model"]="79ai|veo_omni|flash";m.Extra["video_duration"]="8";var parsed=ScenePromptMetadata.Parse(m.Serialize());Assert.Equal("79ai/veo_omni/flash",parsed.Extra["video_model"]);Assert.Equal("8",parsed.Extra["video_duration"]);}
    [Fact] public void Metadata_FromScene_PreservesExtra(){var m=new ScenePromptMetadata{ImagePrompt="img",MotionPrompt="mot"};m.Extra["video_model"]="79ai|veo_3_1|fast";m.Extra["video_duration"]="6";var scene=new VideoProjectSceneDto{ScenePrompt=m.Serialize(),ImagePrompt="img",VideoPrompt="mot"};var from=ScenePromptMetadata.FromScene(scene);Assert.Equal("79ai/veo_3_1/fast",from.Extra["video_model"]);Assert.Equal("6",from.Extra["video_duration"]);}
    private sealed class FakeMon : IOptionsMonitor<VideoRenderOptions>{public VideoRenderOptions CurrentValue{get;}public FakeMon(int d)=>CurrentValue=new VideoRenderOptions{SceneSecondsDefault=d};public VideoRenderOptions Get(string? n)=>CurrentValue;public IDisposable OnChange(Action<VideoRenderOptions,string> l)=>new Nop();private sealed class Nop:IDisposable{public void Dispose(){}}}
    [Fact] public void Resolver_ProjectSceneSeconds_Positive_UsesProject(){var r=new RVideoSceneAddDefaultResolver(new FakeMon(8));var p=new VideoProjectDto{SceneSeconds=12};Assert.Equal(12,r.BuildAddRequest(p,3).DurationSeconds);}
    [Fact] public void Resolver_ProjectSceneSeconds_NonPositive_UsesFallback(){var r=new RVideoSceneAddDefaultResolver(new FakeMon(9));Assert.Equal(9,r.BuildAddRequest(new VideoProjectDto{SceneSeconds=0},1).DurationSeconds);Assert.Equal(9,r.BuildAddRequest(new VideoProjectDto{SceneSeconds=-5},1).DurationSeconds);}
    [Fact] public void Resolver_BothPagesConsumeResolver(){var v2=Read("Components","Pages","RVideo","RVideoV2Preview.razor");var leg=Read("Components","Pages","RenderVideoJobs.razor");Assert.Contains("IRVideoSceneAddDefaultResolver",v2);Assert.Contains("AddDefaults.BuildAddRequest",v2);Assert.Contains("IRVideoSceneAddDefaultResolver",leg);}
    [Fact] public void SharedModelOptionService_BothConsume(){var v2=Read("Components","Pages","RVideo","RVideoV2Preview.razor");var leg=Read("Components","Pages","RenderVideoJobs.razor");Assert.Contains("IRVideoSceneVideoModelOptionsService",v2);Assert.Contains("IRVideoSceneVideoModelOptionsService",leg);Assert.DoesNotContain("ProviderModels.GetModelsAsync",leg);}
}

