$path = 'D:\todoX\Dashboard-web\TodoXPortal\todoX-Dashboard-SaaS\TodoX.Web\Components\Pages\RenderVideoJobs.razor'
$text = [System.IO.File]::ReadAllText($path)
$replacements = @(
    @("chá»n nhÃ¢n váº­t chuáº©n, táº¡o project rá»—ng hoáº·c tÃ¡ch scene, rá»“i render tá»«ng scene.", "chọn nhân vật chuẩn, tạo project rỗng hoặc tách scene, rồi render từng scene."),
    @("ThÃ´ng tin", "Thông tin"),
    @("Vui lÃ²ng Ä‘Äƒng nháº­p.", "Vui lòng đăng nhập."),
    @("NhÃ¢n váº­t", "Nhân vật"),
    @("KhÃ´ng sá»­ dá»¥ng Character", "Không sử dụng Character"),
    @("Chá»n nhÃ¢n váº­t", "Chọn nhân vật"),
    @("Chá»n má»™t Character hoáº¡t Ä‘á»™ng hoáº·c Ä‘á»ƒ trá»‘ng Ä‘á»ƒ táº¡o project khÃ´ng dÃ¹ng Character.", "Chọn một Character hoạt động hoặc để trống để tạo project không dùng Character."),
    @("KhÃ´ng sá»­ dá»¥ng nhÃ¢n váº­t", "Không sử dụng nhân vật"),
    @("Kiá»ƒm tra cáº¥u trÃºc", "Kiểm tra cấu trúc"),
    @("Prompt TodoX há»£p lá»‡.", "Prompt TodoX hợp lệ."),
    @("Prompt thÆ°á»ng.", "Prompt thường."),
    @("JSON khÃ´ng há»£p lá»‡ hoáº·c chÆ°a parse Ä‘Æ°á»£c.", "JSON không hợp lệ hoặc chưa parse được."),
    @("TiÃªu Ä‘á» video", "Tiêu đề video"),
    @("Má»¥c tiÃªu video", "Mục tiêu video"),
    @("Phong cÃ¡ch", "Phong cách"),
    @("Tá»•ng sá»‘ giÃ¢y", "Tổng số giây"),
    @("GiÃ¢y má»—i scene", "Giây mỗi scene"),
    @("Suy nghÄ© ká»‹ch báº£n", "Suy nghĩ kịch bản"),
    @("Táº¡o / phÃ¢n tÃ¡ch scene", "Tạo / phân tách scene"),
    @("Táº¡o má»›i", "Tạo mới"),
    @("ChÆ°a cÃ³ project.", "Chưa có project."),
    @("Log tháo tÃ¡c", "Log thao tác"),
    @("Danh sÃ¡ch job render", "Danh sách job render"),
    @("ChÆ°a cÃ³ job nÃ o cho project nÃ y.", "Chưa có job nào cho project này."),
    @("Báº¯t Ä‘áº§u xá»­ lÃ½", "Bắt đầu xử lý"),
    @("Kiá»ƒm tra Ä‘Äƒng nháº­p", "Kiểm tra đăng nhập"),
    @("Gá»i repository", "Gọi repository"),
    @("HoÃ n táº¥t", "Hoàn tất"),
    @("Táº¡o project thÃ nh cÃ´ng", "Tạo project thành công"),
    @("Táº¡o project rá»—ng", "Tạo project rỗng"),
    @("ÄÃ£ reset form táº¡o project má»›i.", "Đã reset form tạo project mới."),
    @("Táº£i nhÃ¢n váº­t tháº¥t báº¡i", "Tải nhân vật thất bại"),
    @("Táº£i job tháº¥t báº¡i", "Tải job thất bại"),
    @("Báº¯t Ä‘áº§u render áº£nh cho scene", "Bắt đầu render ảnh cho scene"),
    @("Render áº£nh scene", "Render ảnh scene"),
    @("Render khÃ´ng thÃ nh cÃ´ng", "Render không thành công"),
    @("thÃ nh cÃ´ng", "thành công"),
    @("tháº¥t báº¡i", "thất bại"),
    @("lá»—i", "lỗi"),
    @("LÆ°u scene", "Lưu scene"),
    @("LÆ°u", "Lưu"),
    @("XÃ³a", "Xóa"),
    @("LÃªn", "Lên"),
    @("Xuá»‘ng", "Xuống"),
    @("Thiáº¿u file mock scene video. HÃ£y cáº¥u hÃ¬nh VideoRender:MockSceneVideoPath.", "Thiếu file mock scene video. Hãy cấu hình VideoRender:MockSceneVideoPath."),
    @("ÄÃ£ táº¡o job video:", "Đã tạo job video:"),
    @("Xem prompt chuyá»ƒn Ä‘á»™ng", "Xem prompt chuyển động"),
    @("Xem lá»i thoáº¡i", "Xem lời thoại"),
    @("Báº¯t Ä‘áº§u render áº£nh scene", "Bắt đầu render ảnh scene"),
    @("ÄÃ£ lÆ°u scene.", "Đã lưu scene."),
    @("TÃ¡i lÃ m m?", "")
)
foreach ($pair in $replacements) { $text = $text.Replace($pair[0], $pair[1]) }
[System.IO.File]::WriteAllText($path, $text, [System.Text.UTF8Encoding]::new($true))
