CREATE SCHEMA IF NOT EXISTS video_render;

CREATE TABLE IF NOT EXISTS video_render.video_projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL,
    user_id uuid NULL,
    customer_id uuid NULL,
    title text NULL,
    original_prompt text NOT NULL,
    total_seconds int NOT NULL,
    scene_seconds int NOT NULL,
    scene_count int NOT NULL,
    think_scenes boolean NOT NULL DEFAULT true,
    character_id bigint NULL,
    uploaded_character_url text NULL,
    storage_root text NOT NULL,
    public_base text NOT NULL,
    job_folder text NOT NULL,
    status text NOT NULL,
    final_video_url text NULL,
    final_video_path text NULL,
    error_message text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM information_schema.columns
         WHERE table_schema = 'video_render'
           AND table_name = 'video_projects'
           AND column_name = 'id'
           AND column_default IS NULL
    ) THEN
        ALTER TABLE video_render.video_projects ALTER COLUMN id SET DEFAULT gen_random_uuid();
    END IF;

    IF EXISTS (
        SELECT 1
          FROM information_schema.columns
         WHERE table_schema = 'video_render'
         AND table_name = 'video_projects'
           AND column_name = 'character_id'
           AND data_type = 'uuid'
    ) THEN
        ALTER TABLE video_render.video_projects DROP COLUMN character_id;
    END IF;

    ALTER TABLE video_render.video_projects
        ADD COLUMN IF NOT EXISTS character_id bigint NULL;

    IF EXISTS (
        SELECT 1
          FROM information_schema.columns
         WHERE table_schema = 'video_render'
           AND table_name = 'video_project_scenes'
           AND column_name = 'id'
           AND column_default IS NULL
    ) THEN
        ALTER TABLE video_render.video_project_scenes ALTER COLUMN id SET DEFAULT gen_random_uuid();
    END IF;

    IF EXISTS (
        SELECT 1
          FROM information_schema.columns
         WHERE table_schema = 'video_render'
           AND table_name = 'video_project_events'
           AND column_name = 'id'
           AND column_default IS NULL
    ) THEN
        ALTER TABLE video_render.video_project_events ALTER COLUMN id SET DEFAULT gen_random_uuid();
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS video_render.video_project_scenes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES video_render.video_projects(id) ON DELETE CASCADE,
    tenant_id uuid NOT NULL,
    scene_index int NOT NULL,
    title text NULL,
    duration_seconds int NOT NULL,
    scene_prompt text NOT NULL,
    image_prompt text NULL,
    video_prompt text NULL,
    static_image_path text NULL,
    static_image_url text NULL,
    scene_video_path text NULL,
    scene_video_url text NULL,
    status text NOT NULL,
    error_message text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS video_render.video_project_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES video_render.video_projects(id) ON DELETE CASCADE,
    tenant_id uuid NOT NULL,
    event_type text NOT NULL,
    level text NOT NULL DEFAULT 'info',
    message text NOT NULL,
    data_json jsonb NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
