-- Clean rebuild script for video_render phase 1.
-- WARNING: This drops the whole video_render schema and recreates it cleanly.
-- Use this when the existing schema has mismatched types/defaults from older drafts.

DROP SCHEMA IF EXISTS video_render CASCADE;
CREATE SCHEMA video_render;

CREATE TABLE video_render.video_projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL,
    user_id uuid NULL,
    customer_id uuid NULL,
    title text NULL,
    original_prompt text NOT NULL,
    total_seconds int NOT NULL,
    scene_seconds int NOT NULL,
    scene_count int NOT NULL,
    think_scenes boolean NOT NULL DEFAULT true,
    character_id bigint NULL,
    uploaded_character_url text NULL,
    storage_root text NOT NULL,
    public_base text NOT NULL,
    job_folder text NOT NULL,
    status text NOT NULL,
    final_video_url text NULL,
    final_video_path text NULL,
    error_message text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE video_render.video_project_scenes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES video_render.video_projects(id) ON DELETE CASCADE,
    tenant_id uuid NOT NULL,
    scene_index int NOT NULL,
    title text NULL,
    duration_seconds int NOT NULL,
    scene_prompt text NOT NULL,
    image_prompt text NULL,
    video_prompt text NULL,
    static_image_path text NULL,
    static_image_url text NULL,
    scene_video_path text NULL,
    scene_video_url text NULL,
    status text NOT NULL,
    error_message text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE video_render.video_project_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES video_render.video_projects(id) ON DELETE CASCADE,
    tenant_id uuid NOT NULL,
    event_type text NOT NULL,
    level text NOT NULL DEFAULT 'info',
    message text NOT NULL,
    data_json jsonb NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_video_project_scenes_project_index
    ON video_render.video_project_scenes(project_id, scene_index);

CREATE INDEX idx_video_project_events_project_created
    ON video_render.video_project_events(project_id, created_at DESC);

