<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <Content Include="C:\Users\PC\.nuget\packages\microsoft.extensions.logging.abstractions\8.0.1\lib\net8.0\Microsoft.Extensions.Logging.Abstractions.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Microsoft.Extensions.Logging.Abstractions.dll</Link>
    </Content>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>C:\Users\PC\.nuget\packages\microsoft.extensions.logging.abstractions\8.0.1\lib\net8.0\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Npgsql">
      <HintPath>..\..\..\bin\Release\net10.0\Npgsql.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
