param(
    [string]$ConnectionString = $null
)

$ErrorActionPreference = 'Stop'

function Resolve-ProjectRoot {
    return Split-Path -Parent $PSScriptRoot
}

function Get-ConnectionString {
    param([string]$Root)

    if (-not [string]::IsNullOrWhiteSpace($ConnectionString)) {
        return $ConnectionString
    }

    $appSettingsPath = Join-Path $Root 'appsettings.json'
    if (-not (Test-Path $appSettingsPath)) {
        throw "Không tìm thấy appsettings.json. Hãy truyền -ConnectionString thủ công."
    }

    $json = Get-Content $appSettingsPath -Raw | ConvertFrom-Json
    $value = $json.ConnectionStrings.TodoXSaaS
    if ([string]::IsNullOrWhiteSpace($value)) {
        throw "Không đọc được ConnectionStrings:TodoXSaaS từ appsettings.json."
    }

    return $value
}

function Find-NpgsqlDll {
    param([string]$Root)

    $candidates = @(
        (Join-Path $Root 'bin\Release\net10.0\Npgsql.dll'),
        (Join-Path $Root 'publish\Npgsql.dll')
    )

    foreach ($candidate in $candidates) {
        if (Test-Path $candidate) { return $candidate }
    }

    $found = Get-ChildItem -Path $Root -Recurse -Filter Npgsql.dll -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($null -ne $found) { return $found.FullName }

    throw "Không tìm thấy Npgsql.dll. Hãy build/publish project trước."
}

$root = Resolve-ProjectRoot
$cs = Get-ConnectionString -Root $root
$npgsqlDll = Find-NpgsqlDll -Root $root

Add-Type -Path $npgsqlDll

$logFile = Join-Path $PSScriptRoot 'Reset-VideoRenderPhase1.log'
Start-Transcript -Path $logFile -Append | Out-Null

$sql = @'
DROP SCHEMA IF EXISTS video_render CASCADE;
CREATE SCHEMA video_render;

CREATE TABLE video_render.video_projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL,
    user_id uuid NULL,
    customer_id uuid NULL,
    title text NULL,
    original_prompt text NOT NULL,
    total_seconds int NOT NULL,
    scene_seconds int NOT NULL,
    scene_count int NOT NULL,
    think_scenes boolean NOT NULL DEFAULT true,
    character_id bigint NULL,
    uploaded_character_url text NULL,
    storage_root text NOT NULL,
    public_base text NOT NULL,
    job_folder text NOT NULL,
    status text NOT NULL,
    final_video_url text NULL,
    final_video_path text NULL,
    error_message text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE video_render.video_project_scenes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES video_render.video_projects(id) ON DELETE CASCADE,
    tenant_id uuid NOT NULL,
    scene_index int NOT NULL,
    title text NULL,
    duration_seconds int NOT NULL,
    scene_prompt text NOT NULL,
    image_prompt text NULL,
    video_prompt text NULL,
    static_image_path text NULL,
    static_image_url text NULL,
    scene_video_path text NULL,
    scene_video_url text NULL,
    status text NOT NULL,
    error_message text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE video_render.video_project_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES video_render.video_projects(id) ON DELETE CASCADE,
    tenant_id uuid NOT NULL,
    event_type text NOT NULL,
    level text NOT NULL DEFAULT 'info',
    message text NOT NULL,
    data_json jsonb NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_video_project_scenes_project_index
    ON video_render.video_project_scenes(project_id, scene_index);

CREATE INDEX idx_video_project_events_project_created
    ON video_render.video_project_events(project_id, created_at DESC);
'@

$conn = [Npgsql.NpgsqlConnection]::new($cs)
try {
    $conn.Open()
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    $cmd.CommandTimeout = 300
    [void]$cmd.ExecuteNonQuery()
    Write-Host "Đã reset schema video_render thành công." -ForegroundColor Green
}
finally {
    if ($null -ne $conn) { $conn.Dispose() }
    Stop-Transcript | Out-Null
}
